### ISSUE TITLE
Multiple files in torrent?

### ISSUE THREAD

**Issue by kaphacius** [fabiospampinato/cliflix#14]
Is there a way to choose which one I want to watch?
Tried next/previous in VLC

**Comment by fabiospampinato** [comment]
cliflix uses [webtorrent-cli](https://github.com/webtorrent/webtorrent-cli) under the hood for streaming torrents to apps, and it looks like it has a `--select` option for selecting a specific file to stream.

In order to enable this you should call cliflix with `cliflix -- --select`, then when the list of files will be outputted you'll have to pick an index, for instance 4, and call cliflix again with `cliflix -- --select 4`
